name: Prof!
on:
  push:
jobs:
  simple-automation:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Ciao!!"
      - run: echo "ğŸ§ğŸ§ğŸ§ğŸ§ğŸ§ğŸ§"
      - run: echo "Questa Ã¨ la mia prima automazione"
